module.exports = {
  'white': '#fff',
  'primary-color': '#9396f7',
  'processing-color': '#4173da',
  'success-color': 'rgb(100, 178, 133)',
  'error-color': 'rgb(223,85,78)',
  'warning-color': 'rgb(239,169,65)',
  'card-skeleton-bg': 'fade(@white, 35%)',
  'text-color': 'fade(@white, 65%)',
  'text-color-secondary-dark': 'fade(@white, 45%)',
  'body-background': 'rgb(50,60,75)',
  'component-background': 'rgb(40,50,65)',
  'card-padding-base': '16px',
  'border-radius-base': '4px',
  'border-color-base': 'rgba(255,255,255,0.1)',
  'border-color-split': 'rgba(255,255,255,0.2)',
  'btn-primary-shadow': '2px 2px 10px fade(@primary-color, 30%)',
  'popover-background': '@component-background',
  'tooltip-bg': '@component-background',
  'table-header-bg': 'rgba(0,0,0,0.25)',
  'table-row-hover-bg': 'rgba(0,0,0,0.15)',
  'select-clear-background': 'transparent',
  'layout-header-background': 'transparent',
  'layout-footer-background': '@component-background',
}