export const TOOLTIP_KEY = 'tooltip-read-status-'
export const MODAL_VISIBLE_KEY = 'description-modal-visible-'

export const STORAGE_KEYS = {
  AppAgreementConfirmed: '@Global:appAgreementConfirmed',
  AppInstallHint: '@Global:appInstallHint',
  AppMode: '@Global:appMode',
  UserRefreshToken: '@User:refreshToken',
  PhoneVerifySendTime: '@Phone:verifySendTime',
  ProblemSearchHistory: '@Problem:searchHistory',
  ProblemTimer: '@Problem:pearchTimer',
  NoteDraft: '@Note:Draft',
  ModuleSortKey: '@Module:ModuleSortKey',
  ModuleSortOrder: '@Module:ModuleSortOrder',
  ModuleRateSort: '@Module:RateSort',
  RateScoreAvailable: '@Rate:ScoreAvailable',
  RateAvailable: '@Rate:available',
  RateSortKey: '@Rate:SortKey',
  RateSortOrder: '@Rate:SortOrder',
  RateRemarkType: '@Rate:RemarkType',
  RatePageSize: '@Rate:PageSize',
  RateRemarkEdit: '@Rate:RemarkEdit',
  RateRemarkUpdate: '@Rate:RemarkUpdate',
  RateCommentPageSize: '@Rate:RateCommentPageSize',
  RateIsRead: '@Rate:IsRead',
  RateView: '@Rate:View',
  AccountRateSortKey: '@Account:RateSortKey',
  AccountRateSortOrder: '@Account:RateSortOrder',
  ForumSortKey: '@Forum:HomeSortKey',
  TopicCommentPageSize: '@Topic:TopicCommentPageSize',
};
