export enum LanguageCodes {
  AF = 'af',
  SQ = 'sq',
  AR = 'ar',
  EU = 'eu',
  BG = 'bg',
  CA = 'ca',
  ZHCN = 'zh-CN',
  ZHTW = 'zh-TW',
  HR = 'hr',
  CS = 'cs',
  DA = 'da',
  NL = 'nl',
  EN = 'en',
  ET = 'et',
  FI = 'fi',
  FR = 'fr',
  DE = 'de',
  EL = 'el',
  HE = 'he',
  HI = 'hi',
  HU = 'hu',
  IS = 'is',
  IN = 'in',
  IT = 'it',
  JA = 'ja',
  KO = 'ko',
  LV = 'lv',
  LT = 'lt',
  MK = 'mk',
  MS = 'ms',
  NO = 'no',
  PL = 'pl',
  PT = 'pt',
  RM = 'rm',
  RO = 'ro',
  RU = 'ru',
  SR = 'sr',
  SL = 'sl',
  SK = 'sk',
  ES = 'es',
  SV = 'sv',
  TR = 'tr',
  TH = 'th',
  VI = 'vi',
}

export const LanguageCodes_MAP = {
  [LanguageCodes.ZHCN]: '简体中文',
  [LanguageCodes.ZHTW]: '繁体中文',
  [LanguageCodes.EN]: '英语',
  [LanguageCodes.JA]: '日语',
  [LanguageCodes.KO]: '韩语',
  [LanguageCodes.AF]: '南非荷兰语',
  [LanguageCodes.SQ]: '阿尔巴尼亚语',
  [LanguageCodes.AR]: '阿拉伯语',
  [LanguageCodes.EU]: '巴斯克语',
  [LanguageCodes.BG]: '保加利亚语',
  [LanguageCodes.CA]: '加泰罗尼亚语',
  [LanguageCodes.HR]: '克罗地亚语',
  [LanguageCodes.CS]: '捷克语',
  [LanguageCodes.DA]: '丹麦语',
  [LanguageCodes.NL]: '荷兰语',
  [LanguageCodes.ET]: '爱沙尼亚语',
  [LanguageCodes.FI]: '芬兰语',
  [LanguageCodes.FR]: '法语',
  [LanguageCodes.DE]: '德语',
  [LanguageCodes.EL]: '希腊语',
  [LanguageCodes.HE]: '希伯来语',
  [LanguageCodes.HI]: '北印度语',
  [LanguageCodes.HU]: '匈牙利语',
  [LanguageCodes.IS]: '冰岛语',
  [LanguageCodes.IN]: '印度尼西亚语',
  [LanguageCodes.IT]: '意大利语',
  [LanguageCodes.LV]: '拉脱维亚语',
  [LanguageCodes.LT]: '立陶宛语',
  [LanguageCodes.MK]: '马其顿语',
  [LanguageCodes.MS]: '马来语',
  [LanguageCodes.NO]: '挪威语',
  [LanguageCodes.PL]: '波兰语',
  [LanguageCodes.PT]: '葡萄牙语',
  [LanguageCodes.RM]: '罗曼斯方言',
  [LanguageCodes.RO]: '罗马尼亚语',
  [LanguageCodes.RU]: '俄语',
  [LanguageCodes.SR]: '塞尔维亚语',
  [LanguageCodes.SL]: '斯洛伐克语',
  [LanguageCodes.SK]: '斯洛文尼亚语',
  [LanguageCodes.ES]: '西班牙语',
  [LanguageCodes.SV]: '瑞典语',
  [LanguageCodes.TR]: '泰语',
  [LanguageCodes.TH]: '土耳其语',
  [LanguageCodes.VI]: '越南语',
}

